name: build

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    name: test on ${{ matrix.os }} with ${{ matrix.cxx }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cxx: g++
          - os: ubuntu-latest
            cxx: clang++
          - os: macos-latest
            cxx: clang++
      # Do not auto-cancel other runners if one fails
      fail-fast: false

    env:
      CXX: ${{ matrix.cxx }}
      UV_SYSTEM_PYTHON: 1

    steps:
      - name: Disable man-db building
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # This speeds up apt-get, by preventing the man-db step from running
        run: sudo rm -vf /var/lib/man-db/auto-update

      - name: harden runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"
      - uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "latest"

      # Use mold for faster linking
      - uses: rui314/setup-mold@45c2b085bbc0283c8e1443d4a511aaa1eda5a3a1 # v1
        with:
          mold-version: 2.38.0
          make-default: true

      - name: ccache
        uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5 # v1.2.17
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.cxx }}
          create-symlink: true
          # Disable cache cleanups while building
          max-size: "0"

      - name: dependencies (OS specific)
        run: bash scripts/setup-${{ matrix.os }}.sh

      - name: dependencies (common)
        run: bash scripts/setup-common.sh

      - name: build and test
        run: bash scripts/build-common.sh DEBUG=true SANITIZE=true

      - name: CCache cleanup
        # Manual ccache cleanup, using the ccache-action default max size
        run: env CCACHE_MAXSIZE=500M ccache --cleanup
